title: Rock, paper, scissors by hand
hero_image: images/banner.png
description: Combine a model trained using Google’s Teachable Machine with a Python program created on a computer to build an application.
version: 4
listed: true
copyedit: true
last_tested: "2020-06-12"
steps:
  - title: Introduction
  - title: Get set up
  - title: Get inspiration
  - title: Make your model
  - title: Make your application
  - title: Share
  - title: Reflect
    knowledge_quiz:
      path: quiz1
      questions: 3
      passing_score: 3

