title: Rock, paper, scissors by hand
hero_image: images/banner.png
description: Use Google's Teachable Machine to build a rock, paper, scissors game controlled by hand gestures
version: 4
listed: true
copyedit: true
last_tested: "2020-06-12"
steps:
  - title: Introduction
  - title: Get setup
  - title: Get inspiration
  - title: Make your model
  - title: Make your application
  - title: Share
  - title: Reflect

